# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b6daf7cb00a0c0156464ddcc8645e853eac64858ffdfe9e1ab7827f458e54aecda1d5a4437451325d1d78828f8c5469e8601d789042a9ea23f4b0300a7f5440a

test:
  secret_key_base: 89e9cc7540327d15b32069eee5f88b32188b1f50d26e1be990a0a1fcd8d9b86ccd5bdaaca4748b316af67a19d8f2572b3bfc324afbf5a694597b8dfb70061cfd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
